apiVersion: fission.io/v1
kind: MessageQueueTrigger
metadata:
  creationTimestamp: null
  name: kafkatest
  namespace: default
spec:
  contentType: application/json
  cooldownPeriod: 30
  errorTopic: one-seven-error
  functionref:
    functionweights: null
    name: consumer
    type: name
  maxReplicaCount: 100
  maxRetries: 3
  messageQueueType: kafka
  metadata:
    bootstrapServers: my-cluster-kafka-brokers.my-kafka-project.svc:9092
    consumerGroup: my-group
    topic: one-seven-request
  minReplicaCount: 0
  mqtkind: keda
  pollingInterval: 5
  respTopic: one-seven-response
  topic: one-seven-request
